### ISSUE TITLE
iOS: Drag to close does not work after scrolling back up in overflowing content

### ISSUE THREAD

**Issue by andrejilderda** [emilkowalski/vaul#153]
I found that when you try to drag close on iOS after you scroll down and back up to the top of an overflowing content container it does not close. Most of the time a second drag is working, sometimes it gets completely stuck (see first video). 

~~This is a regression that is caused in v.0.7.1 by #137 . Reverting that line fixes the issue (second video).~~ 
_Upon further investigation, the fix below doesn't fully work, especially when the body is overflowing. Still it seems to make things better._

Issue:

https://github.com/emilkowalski/vaul/assets/487182/6d653d0b-398c-4e0d-a98e-49c40c707a46

Fix applied:

https://github.com/emilkowalski/vaul/assets/487182/d14b5e65-99e4-4afe-976f-bf88d19db6d3

**Comment by emilkowalski** [comment]
@andrejilderda Thank you for the reporting and investigating it! 

I think that was actually the cause of it, you are sometimes not allowed to drag it after scrolling, because I've implemented a window of 500ms (`SCROLL_LOCK_TIMEOUT` variable) in which you are not allowed to drag after scrolling to prevent accidentaly closing the drawer. You likely scroll very fast with your thumb and once you reach the top and drag again, because you haven't noticed you are at the top,the velocity would be high enough to close the drawer immidiately.

I've temporarily removed multi touch in this PR #155  and addded an issue to bring it back.

**Comment by andrejilderda** [comment]
Hi @emilkowalski , thanks! It makes things better, but it's not the entire solution to this bug. I'm also pretty sure that it's not the `SCROLL_LOCK_TIMEOUT` that is causing the issue, since setting it to `0` (or disabling it altogether) doesn't solve the issue.

__To reproduce:__

_Note: the reproduction is based on [this branch](https://github.com/andrejilderda/vaul/tree/fix/unable-to-close-drawer-on-ios-under-certain-circumstances-testsuite) and includes the fix proposed in this PR: #154. To test it yourself checkout my fork and see http://localhost:3000/without-scaled-background_

1. Open the console.
2. Scroll down on the page a bit,
3. Open the drawer,
4. Close the drawer,
5. Re-open the drawer,
6. Scroll a bit down inside the drawer and back up to the top,
7. Try drag closing the drawer,
8. Notice how you're unable to scroll the drawer down (you may need to repeat above steps from step 2 (!) on several times before this is the case). Also scrolling inside the drawer does not work.
9. Click anywhere on the drawer and notice that it closes. 🤔
10. The element that is logged to the console is the top-level <html>-element. 🤔

Step 9 & 10 are both unexpected.

https://github.com/emilkowalski/vaul/assets/487182/ebfdcf30-da78-4d02-9227-b68b2fd31670

---

I thought this may be caused by some stale state in the Root context provider. I tried remounting the entire drawer on open (`{open && <Drawer.Root>...}`), and unfortunately I'm still able to reproduce the issue.

I'm willing to dig into this some more, but I'm a bit lost. Do you maybe have ideas what is causing this @emilkowalski ?

**Comment by emilkowalski** [comment]
@andrejilderda I've merged your PR #154, does that solve it? I'm unable to reproduce it

**Comment by emilkowalski** [comment]
Fixed in #167

**Comment by andrejilderda** [comment]
@emilkowalski Hi Emil, unfortunately I'm still able to reproduce the bug in the most recent version. Let me know if you need a new fork with a reproduction.

**Comment by emilkowalski** [comment]
@andrejilderda Yes please, I’m unable to reproduce myself unfortunately

**Comment by andrejilderda** [comment]
@emilkowalski Here you can find the changes to reproduce the issue:
https://github.com/andrejilderda/vaul/commit/a234745f1dec23da5cf263a50a4fd1f2f70ad673

The steps above in https://github.com/emilkowalski/vaul/issues/153#issuecomment-1781261230 still apply as you can see in this video:

https://github.com/emilkowalski/vaul/assets/487182/2423fdab-7eb7-4d76-b464-0ca0fc22c892

**Comment by dan-coman** [comment]
I have the same issue 

> @emilkowalski Here you can find the changes to reproduce the issue: [andrejilderda@a234745](https://github.com/andrejilderda/vaul/commit/a234745f1dec23da5cf263a50a4fd1f2f70ad673)
> 
> The steps above in [#153 (comment)](https://github.com/emilkowalski/vaul/issues/153#issuecomment-1781261230) still apply as you can see in this video:
> 
>  reproduction.mp4

I have the same issue with latest version: 0.9.0 and using shadcn ui. Problem is just on safari mobile, chrome mobile seems to work just fine. Any way to fix this?

**Comment by josuasimatupang** [comment]
Hi @emilkowalski @andrejilderda any update on this issue?

**Comment by andrejilderda** [comment]
@josuasimatupang I tried, but unfortunately I haven't been able to fix this issue. In the end I made my own drawer component that is very similar to vaul but works quite different internally. Might open-source it after successful dogfooding.

**Comment by josuasimatupang** [comment]
@andrejilderda keep it going! waiting for the open-source!

**Comment by andrejilderda** [comment]
Can anyone in this thread confirm if this bug was fixed in v1?

**Comment by andrejilderda** [comment]
Reproduced the bug in v1, but couldn’t replicate it on iOS 18. Looks like the issue is specific to iOS 17 and earlier.
