### ISSUE TITLE
iOS: Overflowing elements flash on drawer close

### ISSUE THREAD

**Issue by ParkerMJones** [emilkowalski/vaul#365]
#### Description of the issue
- iOS only: Elements that exist below the height of the screen, and that overflow off the page horizontally, will flash when the drawer is closed
- Sometimes on opening the drawer with these elements in view, the entire page will flash, and scroll position may be moved
- Tested on Safari, Chrome, and Firefox with same results in each
- Seems only to happen on real devices: the simulator behaves as expected (iPhone 15 Pro Max, iOS 17.2)
- On Android (Galaxy S22, Android 14) and desktop web (Mac M2 OS 14.4.1), the elements behave as expected with no flash (although sometimes scroll position of the page is recalculated on drawer opening on Android)

[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/github/ParkerMJones/vaul-flash-repro)

[Vercel Deployment](https://vaul-flash-repro.vercel.app/)

#### Environment
  - Remix 2.9.2
  - vaul 0.9.1
  - tested on: iPad (9th Gen) OS 17.4.1

[Link to reproduction repository](https://github.com/ParkerMJones/vaul-flash-repro)

#### Video Recording

https://github.com/ParkerMJones/vaul-flash-repro/assets/80937296/dab773e5-94c8-48ea-974e-a7623a07b17d

**Comment by hauseyo** [comment]
Facing the same issue on iPhone 11

**Comment by srkuleo** [comment]
Can confirm this, also happening on my PWA and Safari on Iphone 13. It also doesn't allow me to interact with buttons inside (remove, cancel), only Overlay. It also make a big layout shift on both opening and closing modal.

Like you said, only happening on real devices both in development and production, but doesn't affect desktop nor mobile device mode in DevTools.

I thought it has to do something with setting body position to fixed upon opening modals, but even with noBodyStyles it still occurs. The more I think about it probably it has to do something with locking the scroll behaviour because when I put modal prop to false, everything works fine but I don't think that should be the solution since it disables Overlay. My current solution (a bad one) is to set modal to false, set the state to track whether modal is opened or closed, instead of the Overlay render a div with styles of the Overlay and set the onClick event to handle the state. The only drawback is that page becomes scrollable through "the div overlay", which is annoying I know but at least I can interact with my modal and I don't have to change the whole UI until the fix is provided.

And I hope one comes soon...

**Comment by AdytZZa22** [comment]
Facing the same issue on 13 Pro Max

**Comment by muhammadarsalanmanzoor** [comment]
facing same issue on some android and ios devices

**Comment by renekahr** [comment]
I'm facing the same issue on an iOS device when using the Arc Search browser.

**Comment by landry-fairwinds** [comment]
In addition to the ```open``` and ```onOpenChange``` props, I also added ```disablePreventScroll``` and ```noBodyStyles``` to the root and that helped.

```javascript
<ResponsiveDialogContext.Provider value={{ open, setOpen }}>
    <Drawer open={open} onOpenChange={setOpen} disablePreventScroll noBodyStyles>
        {children}
    </Drawer>
</ResponsiveDialogContext.Provider>
```

**Comment by renekahr** [comment]
@landry-fairwinds worked for me. Thanks for sharing the solution.

**Comment by srkuleo** [comment]
> In addition to the `open` and `onOpenChange` props, I also added `disablePreventScroll` and `noBodyStyles` to the root and that helped.
> 
> ```js
> <ResponsiveDialogContext.Provider value={{ open, setOpen }}>
>     <Drawer open={open} onOpenChange={setOpen} disablePreventScroll noBodyStyles>
>         {children}
>     </Drawer>
> </ResponsiveDialogContext.Provider>
> ```

I don’t think this should be the solution, it basically acts as putting modal={false} on Root component which lets you scroll through the Overlay. 

If that’s the targeted behaviour, then go for it, but personally I wouldn’t want my modals to be able to interact with application behind them.

**Comment by emilkowalski** [comment]
This should be fixed in #341

**Comment by muhammadarsalanmanzoor** [comment]
This is fixed but after this if open a bottomsheet in ios then my page is scrolling to top everytime if i open the bottomsheet and this should happen if i pass both the props disablePreventScroll, noBodyStyles

**Comment by renekahr** [comment]
@emilkowalski What should we adjust now, after the updates? I removed `disablePreventScroll`and `noBodyStyles` now the drawer scrolls to the top and has a very weird behavior. I also can't trigger nested drawers anymore.

**Comment by renekahr** [comment]
@landry-fairwinds `disablePreventScroll` doesn't exist on drawer root. 
<img width="644" alt="image" src="https://github.com/user-attachments/assets/66cf2acb-712a-4c8d-834d-130afaa16b3b">

Any idea how to fix this?

**Comment by tylerbecks** [comment]
I just experienced this issue, adding `disablePreventScroll` to Drawer (I'm using Shadcn) fixes it.

| Before | After |
| - | - |
| https://github.com/user-attachments/assets/21532f3d-43dc-40ea-8a36-c28e7e1187f2 | https://github.com/user-attachments/assets/8c4de29b-ecbd-463c-bfe9-1db902f59905 |

**Comment by tylerbecks** [comment]
I'm currently still experiencing this issue where the drawer flashes while it's dismissing. My suspicion is that state changes that happen mid-dismissal are causing it to flash

![Image](https://github.com/user-attachments/assets/c1d5446a-8d95-4670-ac3c-4259df6ff33a)

**Comment by tylerbecks** [comment]
I found a workaround, inspired by this section in [the Radix Dialog docs](https://www.radix-ui.com/primitives/docs/components/dialog#close-after-asynchronous-form-submission):

```
/**
 * Props for FilterDrawer component
 *
 * This component addresses a UI flash issue that occurs when state changes happen
 * while the drawer is animating closed:
 *
 * Problem: When filter state (e.g., price, score) updates while a drawer is animating closed,
 * the drawer content may flash briefly in incorrect positions, creating a jarring visual effect.
 *
 * Solution: Delay state changes until after drawer animation completes
 * 1. First close the drawer: setOpen(false)
 * 2. Set pendingAction to indicate what action should run after closing (APPLY or RESET)
 * 3. Wait for animation to complete (using timeout matching animation duration)
 * 4. Execute the appropriate action callback (applyAction or resetAction)
 *
 * Usage pattern in filter components:
 * - Define resetAction and applyAction callbacks
 * - On button click, set pendingAction and close the drawer
 * - Let FilterDrawer handle the timing of the action execution
 */
interface FilterDrawerProps {
  applyAction?: () => void;
  children: React.ReactNode;
  onOpenChange: (open: boolean) => void;
  open: boolean;
  pendingAction?: FilterAction | null;
  resetAction?: () => void;
  animationDuration?: number;
}

export function FilterDrawer({
  children,
  open,
  onOpenChange,
  pendingAction,
  resetAction,
  applyAction,
  animationDuration = DRAWER_ANIMATION_DURATION + 1,
  ...props
}: FilterDrawerProps) {
  const handleAnimationEnd = useCallback(() => {
    if (pendingAction === FilterActions.RESET) {
      resetAction?.();
    } else if (pendingAction === FilterActions.APPLY) {
      applyAction?.();
    }
  }, [pendingAction, resetAction, applyAction]);

  useEffect(() => {
    if (open) return;
    setTimeout(() => {
      handleAnimationEnd();
    }, animationDuration);
    // Intentionally ignore handleAnimationEnd
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, pendingAction, animationDuration]);

  return (
    <Drawer open={open} onOpenChange={onOpenChange} {...props}>
      {children}
    </Drawer>
  );
}
```
